# Display
Output .tapes/matthew-henry-gate.gif
Set FontSize 16
Set Width 800
Set Height 500
Set TypingSpeed 175ms

# Run
Type "matthew-henry-gate && echo right || echo wrong"
Enter
Sleep 3s
Type "y"
Enter
Sleep 3s
Hide
Type@50ms "clear"
Enter

Show
Type "matthew-henry-gate && echo right || echo wrong"
Enter
Sleep 3s
Type "y"
Enter
Sleep 3s
Hide
Type@50ms "clear"
Enter

Show
Type "matthew-henry-gate && echo right || echo wrong"
Enter
Sleep 3s
Type "y"
Enter
Sleep 3s
