local ones_we_like = {
  "3024 Night",
  "Afterglow",
  "Afterglow (Gogh)",
  "Andromeda",
  "Apple Classic",
  "Apprentice (base16)",
  "arcoiris",
  "Arthur",
  "Ashes (base16)",
  "Atelier Cave (base16)",
  "Atelier Forest (base16)",
  "Atelier Plateau (base16)",
  "Atelier Savanna (base16)",
  "Atelier Seaside (base16)",
  "Atelierdune (dark) (terminal.sexy)",
  "Atelierforest (dark) (terminal.sexy)",
  "Atelierheath (dark) (terminal.sexy)",
  "ayu",
  "Ayu Dark (Gogh)",
  "Ayu Mirage",
  "Ayu Mirage (Gogh)",
  "Belafonte Night",
  "Bespin (base16)",
  "BirdsOfParadise",
  "Black Metal (base16)",
  "Black Metal (Bathory) (base16)",
  "Black Metal (Nile) (base16)",
  "Bluloco Zsh Light (Gogh)",
  "BlulocoDark",
  "Breath Darker (Gogh)",
  "Breath Silverfox (Gogh)",
  "Breeze (Gogh)",
  "Brewer (base16)",
  "Brogrammer",
  "Brush Trees Dark (base16)",
  "Builtin Dark",
  "Builtin Pastel Dark",
  "Builtin Solarized Light",
  "Cai (Gogh)",
  "Calamity",
  "Canvased Pastel (terminal.sexy)",
  "carbonfox",
  "Catch Me If You Can (terminal.sexy)",
  "Catppuccin Frappe",
  "CGA",
  "Chalk",
  "Chalk (base16)",
  "Chalk (Gogh)",
  "Chalkboard",
  "Chameleon (Gogh)",
  "Ciapre",
  "Circus (base16)",
  "City Streets (terminal.sexy)",
  "Classic Dark (base16)",
  "Classic Light (base16)",
  "Clone Of Ubuntu (Gogh)",
  "Cloud (terminal.sexy)",
  "Cobalt2",
  "Codeschool (base16)",
  "coffee_theme",
  "Color Star (terminal.sexy)",
  "Colorcli (Gogh)",
  "Colorful Colors (terminal.sexy)",
  "Colors (base16)",
  "Count Von Count (terminal.sexy)",
  "CrayonPonyFish",
  "DanQing (base16)",
  "Darcula (base16)",
  "Dark Ocean (terminal.sexy)",
  "Dark Pastel",
  "Dark+",
  "darkmoss (base16)",
  "Darktooth (base16)",
  "Dawn (terminal.sexy)",
  "Deafened (terminal.sexy)",
  "Decaf (base16)",
  "deep",
  "Default Dark (base16)",
  "Dehydration (Gogh)",
  "Derp (terminal.sexy)",
  "Digerati (terminal.sexy)",
  "DimmedMonokai",
  "Dotshare (terminal.sexy)",
  "Dracula",
  "Dracula (Official)",
  "Dracula+",
  "duckbones",
  "DWM rob (terminal.sexy)",
  "Earthsong",
  "Edge Dark (base16)",
  "Ef-Bio",
  "Ef-Dark",
  "Ef-Trio-Dark",
  "Ef-Winter",
  "Eighties (base16)",
  "Eldorado dark (terminal.sexy)",
  "Elemental",
  "Elementary",
  "Elio (Gogh)",
  "Epiphany (terminal.sexy)",
  "Eqie6 (terminal.sexy)",
  "Equilibrium Gray Dark (base16)",
  "Espresso (base16)",
  "Espresso Libre",
  "Everforest Dark (Gogh)",
  "FarSide (terminal.sexy)",
  "Firewatch",
  "Fishbone (terminal.sexy)",
  "FishTank",
  "Flat Remix (Gogh)",
  "Floraverse",
  "ForestBlue",
  "Framer",
  "Framer (base16)",
  "Freya (Gogh)",
  "FrontEndDelight",
  "Galaxy",
  "GitHub Dark",
  "GJM (terminal.sexy)",
  "Glacier",
  "Gogh (Gogh)",
  "Gooey (Gogh)",
  "Google Dark (base16)",
  "Google Dark (Gogh)",
  "Grandshell (terminal.sexy)",
  "Grayscale (light) (terminal.sexy)",
  "Grayscale Dark (base16)",
  "Grayscale Light (base16)",
  "Gruber (base16)",
  "Gruvbox (Gogh)",
  "Gruvbox dark, hard (base16)",
  "Gruvbox dark, medium (base16)",
  "Gruvbox dark, pale (base16)",
  "Gruvbox dark, soft (base16)",
  "Gruvbox Light",
  "Gruvbox Material (Gogh)",
  "GruvboxDark",
  "GruvboxDarkHard",
  "Guezwhoz",
  "Hacktober",
  "Helios (base16)",
  "Hemisu Dark (Gogh)",
  "Highway",
  "Hopscotch.256",
  "Horizon Dark (base16)",
  "Horizon Dark (Gogh)",
  "Humanoid dark (base16)",
  "Hybrid (Gogh)",
  "Hybrid (terminal.sexy)",
  "Icy Dark (base16)",
  "Iiamblack (terminal.sexy)",
  "Insignificato (terminal.sexy)",
  "Invisibone (terminal.sexy)",
  "Isotope (base16)",
  "Ivory Dark (terminal.sexy)",
  "JWR dark (terminal.sexy)",
  "Jackie Brown",
  "Japanesque",
  "Jason Wryan (terminal.sexy)",
  "Jellybeans",
  "JetBrains Darcula",
  "Kanagawa (Gogh)",
  "Kibble",
  "Kimber (base16)",
  "Konsolas",
  "Lab Fox",
  "Later This Evening",
  "Lavandula",
  "London Tube (base16)",
  "Lost Woods (terminal.sexy)",
  "Low Contrast (terminal.sexy)",
  "Lumifoo (terminal.sexy)",
  "Macintosh (base16)",
  "Man Page",
  "Mashup Colors (terminal.sexy)",
  "Material Darker (base16)",
  "Material Vivid (base16)",
  "MaterialDark",
  "MaterialDarker",
  "MaterialDesignColors",
  "MaterialOcean",
  "Mathias",
  "Medallion",
  "Mikado (terminal.sexy)",
  "Mirage",
  "Misterioso",
  "Mocha (base16)",
  "Modus-Vivendi",
  "Molokai",
  "MonaLisa",
  "Mono Theme (terminal.sexy)",
  "Monokai (base16)",
  "Monokai (terminal.sexy)",
  "Monokai Pro (Gogh)",
  "Monokai Pro Ristretto (Gogh)",
  "Monokai Remastered",
  "Monokai Soda",
  "Monokai Vivid",
  "Muse (terminal.sexy)",
  "N0tch2k",
  "Nancy (terminal.sexy)",
  "Nature Suede (terminal.sexy)",
  "Navy and Ivory (terminal.sexy)",
  "Nebula (base16)",
  "Nord (base16)",
  "Nova (base16)",
  "Nucolors (terminal.sexy)",
  "Numix Darkest (terminal.sexy)",
  "Obsidian",
  "Ocean Dark (Gogh)",
  "Oceanic-Next",
  "One Dark (Gogh)",
  "One Half Black (Gogh)",
  "OneDark (base16)",
  "Operator Mono Dark",
  "Orangish (terminal.sexy)",
  "Pali (Gogh)",
  "Panda (Gogh)",
  "Papercolor Dark (Gogh)",
  "Parker Brothers (terminal.sexy)",
  "Pastel White (terminal.sexy)",
  "Paul Millr (Gogh)",
  "PaulMillr",
  "PencilDark",
  "Peppermint (Gogh)",
  "Peppermint",
  "Phrak1 (terminal.sexy)",
  "Pnevma",
  "Poimandres",
  "Pop (base16)",
  "Predawn (Gogh)",
  "Pretty and Pastel (terminal.sexy)",
  "Pro",
  "Pulp (terminal.sexy)",
  "Purpledream (base16)",
  "Qualia (base16)",
  "Railscasts (base16)",
  "Rasi (terminal.sexy)",
  "Red Phoenix (terminal.sexy)",
  "Red Planet",
  "Rippedcasts",
  "Rydgel (terminal.sexy)",
  "SeaShells",
  "Sequoia Monochrome",
  "Seti UI (base16)",
  "Seti",
  "Shaman",
  "Shapeshifter (dark) (terminal.sexy)",
  "Shic (terminal.sexy)",
  "Simple Rainbow (terminal.sexy)",
  "SleepyHollow",
  "Smyck (Gogh)",
  "Smyck",
  "Snazzy (Gogh)",
  "SoftServer",
  "Solarized Darcula",
  "Solarized Dark - Patched",
  "Solarized Dark Higher Contrast",
  "Sonokai (Gogh)",
  "SpaceGray",
  "Spacedust",
  "Spacemacs (base16)",
  "Splurge (terminal.sexy)",
  "Srcery (Gogh)",
  "Subliminal",
  "Summer Pop (Gogh)",
  "Summerfruit Dark (base16)",
  "Sundried",
  "Swayr (terminal.sexy)",
  "Sweet Terminal (Gogh)",
  "Tango (terminal.sexy)",
  "Tangoesque (terminal.sexy)",
  "Tartan (terminal.sexy)",
  "Terminix Dark (Gogh)",
  "Tinacious Design (Dark)",
  "Tomorrow (dark) (terminal.sexy)",
  "Treehouse",
  "UltraDark",
  "UltraViolent",
  "UnderTheSea",
  "Unikitty Dark (base16)",
  "Unikitty Reversible (base16)",
  "Ura (Gogh)",
  "VWbug (terminal.sexy)",
  "Vacuous 2 (terminal.sexy)",
  "VibrantInk",
  "Vice Alt (base16)",
  "Violet Dark",
  "VisiBone (terminal.sexy)",
  "Visibone Alt. 2 (terminal.sexy)",
  "Vs Code Dark+ (Gogh)",
  "WarmNeon",
  "Wez",
  "WildCherry",
  "Windows 10 (base16)",
  "Windows 95 (base16)",
  "Windows High Contrast (base16)",
  "Windows NT (base16)",
  "Woodland (base16)",
  "Wryan",
  "X::DotShare (terminal.sexy)",
  "X::Erosion (terminal.sexy)",
  "Zenburn (base16)",
  "hund (terminal.sexy)",
  "summercamp (base16)",
  "theme2 (terminal.sexy)",
  "thwump (terminal.sexy)",
  "vimbones",
  "wilmersdorf",
  "zenbones_dark",
  "zenburn (terminal.sexy)",
  "zenburned",
  "zenwritten_dark",
}
