return {
  light = {
    "Bluloco Zsh Light (Gogh)",
    "Builtin Solarized Light",
    "Classic Light (base16)",
    "coffee_theme",
    "Colorcli (Gogh)",
    "Grayscale (light) (terminal.sexy)",
    "Grayscale Light (base16)",
    "Gruvbox (Gogh)",
    "Gruvbox Light",
    "Man Page",
    "Simple Rainbow (terminal.sexy)",
    "Ura (Gogh)",
    "vimbones",
  },
  monochrome = {
    "City Streets (terminal.sexy)",
    "Cloud (terminal.sexy)",
    "Count Von Count (terminal.sexy)",
    "Deafened (terminal.sexy)",
    "FarSide (terminal.sexy)",
    "Grayscale Dark (base16)",
    "Icy Dark (base16)",
    "Insignificato (terminal.sexy)",
    "Medallion",
    "MonaLisa",
    "Mono Theme (terminal.sexy)",
    "N0tch2k",
    "Nature Suede (terminal.sexy)",
    "Red Phoenix (terminal.sexy)",
    "Sequoia Monochrome",
    "VWbug (terminal.sexy)",
    "Canvased Pastel (terminal.sexy)",
    "Catch Me If You Can (terminal.sexy)",
  },
  gray = {
    "Afterglow (Gogh)",
    "arcoiris",
    "Arthur",
    "Atelier Forest (base16)",
    "Atelier Plateau (base16)",
    "Atelierforest (dark) (terminal.sexy)",
    "Bespin (base16)",
    "BirdsOfParadise",
    "Breeze (Gogh)",
    "Chalk",
    "Chalk (Gogh)",
    "Chameleon (Gogh)",
    "DanQing (base16)",
    "Dark+",
    "Darktooth (base16)",
    "Dawn (terminal.sexy)",
    "Decaf (base16)",
    "Default Dark (base16)",
    "Dehydration (Gogh)",
    "DimmedMonokai",
    "Dracula+",
    "Earthsong",
    "Edge Dark (base16)",
    "Eighties (base16)",
    "Eldorado dark (terminal.sexy)",
    "Elemental",
    "Elementary",
    "Eqie6 (terminal.sexy)",
    "Equilibrium Gray Dark (base16)",
    "Espresso (base16)",
    "Espresso Libre",
    "GJM (terminal.sexy)",
    "Google Dark (base16)",
    "Google Dark (Gogh)",
    "Gruvbox dark, hard (base16)",
    "Gruvbox dark, medium (base16)",
    "Gruvbox dark, pale (base16)",
    "Gruvbox dark, soft (base16)",
    "GruvboxDark",
    "Highway",
    "Helios (base16)",
    "Guezwhoz",
    "GruvboxDarkHard",
  },
  black = {
    "ayu",
    "Ayu Dark (Gogh)",
    "Brewer (base16)",
    "Brogrammer",
    "Builtin Dark",
    "Builtin Pastel Dark",
    "carbonfox",
    "CGA",
    "Chalk (base16)",
    "Circus (base16)",
    "Classic Dark (base16)",
    "Color Star (terminal.sexy)",
    "Colorful Colors (terminal.sexy)",
    "Colors (base16)",
    "Dark Pastel",
    "deep",
    "Derp (terminal.sexy)",
    "Digerati (terminal.sexy)",
    "Dotshare (terminal.sexy)",
    "DWM rob (terminal.sexy)",
    "Ef-Bio",
    "Ef-Dark",
    "Ef-Trio-Dark",
    "Epiphany (terminal.sexy)",
    "Fishbone (terminal.sexy)",
    "ForestBlue",
    "Framer",
    "FrontEndDelight",
    "GitHub Dark",
    "Glacier",
    "Hybrid (terminal.sexy)",
    "Hybrid (Gogh)",
    "Hacktober",
    "Hemisu Dark (Gogh)",
  },
  dark = {
    "Afterglow",
    "Iiamblack (terminal.sexy)",
    "Invisibone (terminal.sexy)",
    "Isotope (base16)",
    "Ivory Dark (terminal.sexy)",
    "JWR dark (terminal.sexy)",
    "Japanesque",
    "Jason Wryan (terminal.sexy)",
    "Jellybeans",
    "JetBrains Darcula",
    "Kibble",
    "Kimber (base16)",
    "Konsolas",
    "Lab Fox",
    "Later This Evening",
    "London Tube (base16)",
    "Lost Woods (terminal.sexy)",
    "Low Contrast (terminal.sexy)",
    "Lumifoo (terminal.sexy)",
    "Macintosh (base16)",
    "Mashup Colors (terminal.sexy)",
    "Material Darker (base16)",
    "Material Vivid (base16)",
    "MaterialDark",
    "MaterialDarker",
    "Mathias",
    "Mikado (terminal.sexy)",
    "Mocha (base16)",
    "Modus-Vivendi",
    "Molokai",
    "Monokai (base16)",
    "Monokai (terminal.sexy)",
    "Monokai Pro (Gogh)",
    "Monokai Remastered",
    "Monokai Soda",
    "Monokai Vivid",
    "Muse (terminal.sexy)",
    "Nancy (terminal.sexy)",
    "Nord (base16)",
    "Nucolors (terminal.sexy)",
    "Numix Darkest (terminal.sexy)",
    "One Dark (Gogh)",
    "One Half Black (Gogh)",
    "Operator Mono Dark",
    "Orangish (terminal.sexy)",
    "Panda (Gogh)",
    "Papercolor Dark (Gogh)",
    "Parker Brothers (terminal.sexy)",
    "Pastel White (terminal.sexy)",
    "Paul Millr (Gogh)",
    "PaulMillr",
    "PencilDark",
    "Peppermint (Gogh)",
    "Peppermint",
    "Phrak1 (terminal.sexy)",
    "Pnevma",
    "Pop (base16)",
    "Predawn (Gogh)",
    "Pretty and Pastel (terminal.sexy)",
    "Pro",
    "Pulp (terminal.sexy)",
    "Qualia (base16)",
    "Railscasts (base16)",
    "Rasi (terminal.sexy)",
    "Red Planet",
    "Rippedcasts",
    "Rydgel (terminal.sexy)",
    "SeaShells",
    "Seti UI (base16)",
    "Shapeshifter (dark) (terminal.sexy)",
    "Shic (terminal.sexy)",
    "SleepyHollow",
    "Smyck (Gogh)",
    "Smyck",
    "Spacemacs (base16)",
    "Splurge (terminal.sexy)",
    "Srcery (Gogh)",
    "Summer Pop (Gogh)",
    "Summerfruit Dark (base16)",
    "Sundried",
    "Swayr (terminal.sexy)",
    "Tango (terminal.sexy)",
    "Tangoesque (terminal.sexy)",
    "Tartan (terminal.sexy)",
    "Terminix Dark (Gogh)",
    "Tomorrow (dark) (terminal.sexy)",
    "Treehouse",
    "UltraDark",
    "UltraViolent",
    "UnderTheSea",
    "Unikitty Dark (base16)",
    "Vacuous 2 (terminal.sexy)",
    "VibrantInk",
    "Vice Alt (base16)",
    "Violet Dark",
    "VisiBone (terminal.sexy)",
    "Visibone Alt. 2 (terminal.sexy)",
    "Vs Code Dark+ (Gogh)",
    "WarmNeon",
    "Wez",
    "Windows 10 (base16)",
    "Windows 95 (base16)",
    "Windows High Contrast (base16)",
    "Windows NT (base16)",
    "Woodland (base16)",
    "Wryan",
    "X::DotShare (terminal.sexy)",
    "X::Erosion (terminal.sexy)",
    "Zenburn (base16)",
    "hund (terminal.sexy)",
    "summercamp (base16)",
    "theme2 (terminal.sexy)",
    "thwump (terminal.sexy)",
    "zenbones_dark",
    "zenburn (terminal.sexy)",
    "zenburned",
    "zenwritten_dark",
    "3024 Night",
  },
  fun = {
    "WildCherry",
    "Floraverse",
    "Framer (base16)",
  },
}
