const messages = [
  // One word
  "Absconding...",
  "Absquatulating...",
  "Amalgamating...",
  "Ambling...",
  "Angling...",
  "Bamboozling...",
  "Battering...",
  "Bedazzling...",
  "Bedoodling...",
  "Befuddling...",
  "Beguiling...",
  "Bewitching...",
  "Biffing...",
  "Blathering...",
  "Blithering...",
  "Blorping...",
  "Boffing...",
  "Bonking...",
  "Bouldering...",
  "Brewing...",
  "Brimming...",
  "Bubbling...",
  "Bumbling...",
  "Bungling...",
  "Burbling...",
  "Bustling...",
  "Canoodling...",
  "Channelling...",
  "Chattering...",
  "Clamoring...",
  "Clanking...",
  "Clattering...",
  "Clomping...",
  "Clunking...",
  "Cogitating...",
  "Combobulating...",
  "Concocting...",
  "Confabulating...",
  "Contemplating...",
  "Coruscating...",
  "Crumbling...",
  "Dangling...",
  "Dawdling...",
  "Daydreaming...",
  "Defenestrating...",
  "Dillydallying...",
  "Discombobulating...",
  "Dithering...",
  "Doing...",
  "Doodling...",
  "Drumming...",
  "Effervescing...",
  "Enamoring...",
  "Enchanting...",
  "Extemporizing...",
  "Faffing...",
  "Feathering...",
  "Fermenting...",
  "Fiddling...",
  "Figgling...",
  "Finagling...",
  "Fizzing...",
  "Flattering...",
  "Flibbertigibbeting...",
  "Flittering...",
  "Flonking...",
  "Flummoxing...",
  "Flumping...",
  "Foraging...",
  "Fossicking...",
  "Freestyling...",
  "Frittering...",
  "Frolicking...",
  "Fumbling...",
  "Futzing...",
  "Galumphing...",
  "Gamboling...",
  "Gestating...",
  "Gibbering...",
  "Glamoring...",
  "Glimmering...",
  "Glittering...",
  "Glurping...",
  "Gonkulating...",
  "Grooving...",
  "Grumbling...",
  "Gurgling...",
  "Hammering...",
  "Hatching...",
  "Heathering...",
  "Higgling...",
  "Honking...",
  "Humbling...",
  "Humming...",
  "Hustling...",
  "Imagining...",
  "Improvising...",
  "Jabbering...",
  "Jamming...",
  "Jangling...",
  "Jiggling...",
  "Jingling...",
  "Jittering...",
  "Jostling...",
  "Jumbling...",
  "Jungling...",
  "Kerfuffling...",
  "Kerplunking...",
  "Kibbitzing...",
  "Kingling...",
  "Leathering...",
  "Lollygagging...",
  "Luminescing...",
  "Lurking...",
  "Malingering...",
  "Mangling...",
  "Marinating...",
  "Mattering...",
  "Meandering...",
  "Mesmerizing...",
  "Miffing...",
  "Mingling...",
  "Moldering...",
  "Moseying...",
  "Mulling...",
  "Mumbling...",
  "Musing...",
  "Mystifying...",
  "Nattering...",
  "Niggling...",
  "Noodging...",
  "Noodling...",
  "Numbing...",
  "Oscillating...",
  "Pattering...",
  "Perambulating...",
  "Percolating...",
  "Perplexing...",
  "Persnicketing...",
  "Phosphorescing...",
  "Piggling...",
  "Pirouetting...",
  "Pizzazzing...",
  "Plonking...",
  "Plumbing...",
  "Pondering...",
  "Pontificating...",
  "Pottering...",
  "Primming...",
  "Procrastinating...",
  "Pulsating...",
  "Puttering...",
  "Rattling...",
  "Razzmatazzing...",
  "Recombobulating...",
  "Ricocheting...",
  "Ringling...",
  "Rumbling...",
  "Ruminating...",
  "Rummaging...",
  "Rustling...",
  "Sashaying...",
  "Sauntering...",
  "Scampering...",
  "Scattering...",
  "Scavenging...",
  "Schlepping...",
  "Schlurping...",
  "Schmalzing...",
  "Schmoozing...",
  "Scintillating...",
  "Scribbling...",
  "Shattering...",
  "Shimmering...",
  "Shimmying...",
  "Shouldering...",
  "Simmering...",
  "Singling...",
  "Skedaddling...",
  "Skimming...",
  "Skittering...",
  "Skulking...",
  "Sleuthing...",
  "Slithering...",
  "Smoldering...",
  "Snazzifying...",
  "Snorkeling...",
  "Snurfling...",
  "Somersaulting...",
  "Sparkling...",
  "Spelunking...",
  "Splattering...",
  "Splooshing...",
  "Splorfing...",
  "Splunging...",
  "Squelching...",
  "Squiggling...",
  "Squonking...",
  "Stammering...",
  "Steeping...",
  "Struggling...",
  "Strumming...",
  "Stumbling...",
  "Sublimating...",
  "Swashbuckling...",
  "Swooshing...",
  "Synthesizing...",
  "Tangling...",
  "Tattering...",
  "Teetering...",
  "Tethering...",
  "Thrumming...",
  "Thumbing...",
  "Thunking...",
  "Thwacking...",
  "Tingling...",
  "Tinkering...",
  "Tittering...",
  "Tottering...",
  "Traipsing...",
  "Transmuting...",
  "Trimming...",
  "Tumbling...",
  "Twittering...",
  "Unbefuddling...",
  "Undulating...",
  "Vamoosing...",
  "Vibing...",
  "Wangling...",
  "Weathering...",
  "Whimming...",
  "Whirring...",
  "Whomping...",
  "Whooshing...",
  "Wibbling...",
  "Wiggling...",
  "Withering...",
  "Wobbling...",
  "Woolgathering...",
  "Wrangling...",
  "Wriggling...",
  "Yammering...",
  "Yodeling...",
  "Zigzagging...",
  "Zonking...",
  "Zorping...",

  // Phrase
  "Absolving the abstractions...",
  "Abyss staring back...",
  "Achieving enlightenment...",
  "Adding a dash of elegance...",
  "Adjusting the cosmic frequency...",
  "Aerating the arrays...",
  "Aging the algorithms gracefully...",
  "Aligning the chakras...",
  "Anointing the algorithms...",
  "Appeasing the garbage collector...",
  "Archeologically analyzing the architecture...",
  "Ascending to a higher plane...",
  "Asking the electrons...",
  "Asking the hamsters to run faster...",
  "Backpacking through the binaries...",
  "Baking at 350 kilobytes...",
  "Baptizing the binary...",
  "Barbecuing the bugs...",
  "Bargaining with fate...",
  "Believing really hard...",
  "Bewitching the boolean logic...",
  "Blanching the branches...",
  "Blessing the build process...",
  "Bottling the buffers...",
  "Braising the breakpoints...",
  "Bribing the byte fairies...",
  "Bribing the compiler...",
  "Bribing the runtime...",
  "Bungee jumping into the backend...",
  "Buttering up the firewall...",
  "Caffeinating...",
  "Calibrating the flux capacitor...",
  "Camping in the codebase...",
  "Canning the constants...",
  "Caramelizing the callbacks...",
  "Channeling the ancient developers...",
  "Charging the crystals...",
  "Charming the curly braces...",
  "Checking under the hood...",
  "Cherry-picking the commits...",
  "Cleansing the closures...",
  "Communing with the machine spirit...",
  "Consecrating the callbacks...",
  "Consulting ancient scrolls...",
  "Consulting the oracle...",
  "Consulting the rubber duck...",
  "Consulting the void...",
  "Convincing the pixels to cooperate...",
  "Cracking the conundrums...",
  "Cross-examining the debugger...",
  "Curing the code smells...",
  "Cursing the cache misses...",
  "Dancing with dependencies...",
  "Decanting the data structures...",
  "Decoding the mysteries...",
  "Decorating the deployment...",
  "Discovering hidden semicolons...",
  "Divining the answer...",
  "Doing the deployment dance...",
  "Dowsing for bugs...",
  "Drizzling debug sauce...",
  "Dusting off the neurons...",
  "Emancipating the enums...",
  "Enchanting the error handlers...",
  "Excavating ancient APIs...",
  "Existentially questioning...",
  "Exorcising the exceptions...",
  "Experiencing a flash of insight...",
  "Feeding the machine...",
  "Flambéing the failures...",
  "Flattering the floating points...",
  "Flirting with the database...",
  "Folding in the features...",
  "Forgiving the for loops...",
  "Fossil hunting in the functions...",
  "Freeing the functions...",
  "Frosting the functions...",
  "Garnishing the getters...",
  "Giving the code a pep talk...",
  "Glamping in the globals...",
  "Glazing the graphics...",
  "Greasing the gears...",
  "Grilling the glitches...",
  "Hang gliding through the heap...",
  "Harvesting the outputs...",
  "Having a little think...",
  "Having a moment of clarity...",
  "Having words with the cache...",
  "Herding cats in memory...",
  "Herding pointers...",
  "Hexing the hexadecimals...",
  "Hiking through the headers...",
  "Hoping for the best...",
  "Hypnotizing the hash tables...",
  "Icing the interfaces...",
  "Interrogating the stack trace...",
  "Invoking elder functions...",
  "Jarring the JavaScript...",
  "Jinxing the JSON parsers...",
  "Kicking the tires...",
  "Kneading the namespaces...",
  "Letting the dough rise...",
  "Letting the logic breathe...",
  "Liberating the lambdas...",
  "Lobbying the scheduler...",
  "Making offerings to the CI...",
  "Manifesting solutions...",
  "Massaging the heap...",
  "Maturing the methods...",
  "Mesmerizing the memory banks...",
  "Mountain climbing the modules...",
  "Negotiating with cosmic rays...",
  "Negotiating with deadlines...",
  "Negotiating with entropy...",
  "Nurturing the algorithm...",
  "Oiling the cogs...",
  "Parasailing past the parameters...",
  "Pardoning the pointers...",
  "Performing arcane rituals...",
  "Petitioning the kernel...",
  "Pickling the packages...",
  "Picnicking with the processes...",
  "Planting computational seeds...",
  "Plating the output nicely...",
  "Pleading with the logs...",
  "Poaching the pointers...",
  "Polishing the algorithms...",
  "Politely asking the CPU...",
  "Praying to the uptime gods...",
  "Presenting with pizzazz...",
  "Preserving the protocols...",
  "Proofing the promises...",
  "Pruning the decision branches...",
  "Purifying the parameters...",
  "Raising the exceptions...",
  "Reading tea leaves...",
  "Reading the room...",
  "Rearranging deck chairs...",
  "Reasoning with the memory...",
  "Receiving transmissions from the cloud...",
  "Redeeming the recursion...",
  "Releasing the references...",
  "Reticulating splines...",
  "Reversing the polarity...",
  "Ripening the results...",
  "Roasting the race conditions...",
  "Rolling out the runtime...",
  "Sacrificing to the demo gods...",
  "Sanctifying the source code...",
  "Sautéing the syntax errors...",
  "Schmoozing the network...",
  "Scrying the codebase...",
  "Scuba diving in the data...",
  "Searing the segments...",
  "Seasoning the solutions...",
  "Seducing the semicolons...",
  "Serenading the syntax...",
  "Shaking loose the cobwebs...",
  "Shaking the magic 8-ball...",
  "Shuffling bits around...",
  "Skateboarding down the stack trace...",
  "Skydiving through the source...",
  "Smoking the subroutines...",
  "Snorkeling through the streams...",
  "Snowboarding through the schemas...",
  "Solving the riddles of RAM...",
  "Spellbinding the stack frames...",
  "Spelunking through the stack...",
  "Spicing up the specs...",
  "Spinning up the squirrels...",
  "Sprinkling some magic dust...",
  "Squinting at the problem...",
  "Staring into the abyss...",
  "Stoking the furnace...",
  "Stroking chin thoughtfully...",
  "Summoning semicolons...",
  "Surfing the syntax waves...",
  "Sweet-talking the API...",
  "Taking the bytes out for lunch...",
  "Taming wild pointers...",
  "Tangoing with type errors...",
  "Teaching electrons new tricks...",
  "Teaching old code new tricks...",
  "Tickling the stack...",
  "Topping with tests...",
  "Transcending mere computation...",
  "Trekking through the trees...",
  "Tuning the vibrations...",
  "Unbinding the variables...",
  "Unearthing buried bugs...",
  "Unlocking the secrets of silicon...",
  "Unraveling the regex...",
  "Untangling spaghetti...",
  "Untying the type knots...",
  "Waiting for a sign...",
  "Waltzing through the codebase...",
  "Warming up the hamsters...",
  "Watering the logic tree...",
  "Waxing philosophical...",
  "Whisking the widgets...",
  "Whispering passwords to the void...",
  "Whispering sweet nothings to the compiler...",
  "Whispering to the bits...",
  "Willing it into existence...",
  "Winding up the clockwork...",
  "Wining and dining the servers...",
  "Wooing the while loops...",
];

function pickRandom() {
  return messages[Math.floor(Math.random() * messages.length)];
}

export default function (pi) {
  pi.on("turn_start", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(pickRandom());
  });

  pi.on("turn_end", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(); // Reset for next time
  });
}
