#!/bin/bash

if [[ "$1" == "copy" ]]; then
  if is termux ; then
    termux-clipboard-set
  elif is wsl ; then
    clip.exe
  elif is linux ; then
    xclip -sel clip
  fi
else
  if is termux ; then
    termux-clipboard-get
  elif is wsl ; then
    powershell.exe Get-Clipboard | dos2unix
  elif is linux ; then
    xclip -sel clip -o
  fi
fi
