#!/bin/bash

PREFERENCES="&include-passage-references=false&include-verse-numbers=false&include-footnotes=false&include-headings=false";
QUERY="/v3/passage/text/?q=$1";
shift;

for arg in "$@"; do
  QUERY+="+$arg";
done

VERSES=$(curl -H "Authorization: Token 7bf823cec4289f8fbce0b802be2cdeb22fd79c5b" "https://api.esv.org$QUERY$PREFERENCES" 2> /dev/null | jq -r .passages[0])

echo -e "$VERSES"
