#!/bin/bash

preferences="&page-size=100";
query="/v3/passage/search/?q=$1";
shift;

for arg in "$@"; do
  query+="+$arg";
done

verses=$(curl -H "Authorization: Token 7bf823cec4289f8fbce0b802be2cdeb22fd79c5b" "https://api.esv.org$query$preferences" 2> /dev/null | jq -r '.results[] | "\(.content)\n\(.reference)\n"')

echo -e "$verses"
