#!/usr/bin/env bash

# Features
# - tmux popup to search docs 
# - ability to send selected docs to a nvim server
DOCS='~/projects/gitlab/doc/api'
RELOAD="reload:rg --column --color=always --smart-case {q} $DOCS || :"
OPENER='if [[ $FZF_SELECT_COUNT -eq 0 ]]; then
          nvim -M {1} +{2}     # No selection. Open the current line in Vim.
        else
          nvim -M +cw -q {+f}  # Build quickfix list for the selected items.
        fi'
fzf --disabled --ansi --multi \
    --bind "start:$RELOAD" --bind "change:$RELOAD" \
    --bind "enter:become:$OPENER" \
    --bind "ctrl-o:execute:$OPENER" \
    --bind 'alt-a:select-all,alt-d:deselect-all,ctrl-/:toggle-preview' \
    --delimiter : \
    --preview 'bat --style=full --color=always --highlight-line {2} {1}' \
    --preview-window '~4,+{2}+4/3,<80(up)'
