#!/bin/env sh

is_git_repo() {
  git rev-parse --is-inside-work-tree > /dev/null 2>&1
}

branch() {
  git symbolic-ref HEAD --short 2>/dev/null
}

# <https://stackoverflow.com/a/59115583>
rebase-branch-old() {
  path=$(git rev-parse --git-path rebase-apply) # rebase.backend is apply
  if test -d ${path}; then
    revision=$(<${path}/head-name)
    echo ${revision##refs/heads/}
  fi
}

# <https://stackoverflow.com/a/59115583>
rebase-branch-new() {
  path=$(git rev-parse --git-path rebase-merge) # rebase.backend is merge
  if test -d ${path}; then
    revision=$(<${path}/head-name)
    echo ${revision##refs/heads/}
  fi
}

changes() {
  STAGED="$(git diff --cached --name-only 2>/dev/null | wc --lines)s"
  WORKTREE="$(git diff --name-only 2>/dev/null | wc --lines)w"
  UNTRACKED="$(git ls-files --others  --exclude-standard 2>/dev/null | wc --lines)u"
  AHEAD_BEHIND="$(git rev-list --left-right --count @...@{u} | sed -E 's/^([0-9]+)/\1a/; s/\s+([0-9]+)$/\1b/')"
  echo "${STAGED}${WORKTREE}${UNTRACKED}${AHEAD_BEHIND}" | sed -E ':1; s/(^|[^0-9])0[swuab]/\1/g; t1;'
}

if ! is_git_repo; then
  exit
fi

PROMPT=$(branch)
REBASE_BRANCH=$(rebase-branch-new)
REBASE_BRANCH_OLD=$(rebase-branch-old)
if [[ -n "$REBASE_BRANCH" ]]; then
  PROMPT="$REBASE_BRANCH [rebasing]"
elif [[ -n "$REBASE_BRANCH_OLD" ]]; then
  PROMPT="$REBASE_BRANCH_OLD [*rebasing]"
elif git rev-parse --quiet --verify MERGE_HEAD > /dev/null 2>&1; then
  PROMPT="$PROMPT [merging]"
fi
CHANGES=$(changes)
if [[ -n "$CHANGES" ]]; then
  PROMPT="$PROMPT ($CHANGES)"
fi
echo "$PROMPT"
