#!/bin/bash

set -e

is_termux()
{
  command -v termux-setup-storage > /dev/null
}

is_wsl()
{
  command -v wslpath > /dev/null
}

is_linux()
{
  [ "$(uname -s)" = Linux ]
}

is_pair_friendly()
{
  [ -f ~/.pair-nice-with-the-other-kids ]
}

is_lonely()
{
  ! is_pair_friendly
}

is_ssh()
{
  if [ -z "${SSH_CLIENT+x}" ]; then
    return 1
  fi
  return 0
}

is_tmux()
{
  if command -v tmux > /dev/null && [ -z "${TMUX+x}" ]; then
    return 1
  fi
  return 0
}

fn="is_$1"
declare -F "$fn" > /dev/null || {
  echo "is: unknown check: $1"
  exit 2
}
"$fn"

