#!/bin/bash

word=$1
length=${#word}
firstLetters=${word:0:1}

cat ~/scripts/words.txt | \
sed -n "/^${firstLetters}.*/p" | \
awk "{ if (length(\$0) < ${length} + 1) print }" | \
while IFS= read -r line; do 
  if (($(levenshtein $line $word) < 3)); then 
    echo "$line"; 
  fi 
done
