#!/usr/bin/env sh

FILE=$1
LINE=$2

if [ "$LINE" = "" ]; then
  ~/.local/share/mise/installs/neovim/nightly/bin/nvim $(wslpath -u $FILE)
else
  ~/.local/share/mise/installs/neovim/nightly/bin/nvim +$LINE $(wslpath -u $FILE)
fi
