#!/bin/bash

command=$1

set -e

case "${command}" in
  "get")
    token=$(bw unlock --raw);
    query="${@:2}";
    result=$(bw list items --search "${query}" --session ${token} | jq 'map({name, username: .login.username, password: .login.password})');
    countOfResults=$(echo "${result}" | jq '. | length');
    if [ "${countOfResults}" -eq "1" ]; then
      echo "${result}" | jq '.[0] | .name';
      echo "${result}" | jq --raw-output '.[0] | .username';
      echo "${result}" | jq --raw-output '.[0] | .password' | clip.exe;
      echo "Password copied!";
    else
      echo "${result}" | jq '.[] | .name';
      echo "Be more specific";
    fi
    ;;
  "create")
    token=$(bw unlock --raw);
    name=$2;
    user=$3;
    password=$4;
    bw get template item --session ${token} | jq ".login = $(bw get template item.login --session ${token}) | .name = \"${name}\" | .notes = \"\" | .login.username = \"${user}\" | .login.password = \"${password}\" | .login.totp = \"NONSPEAKERCUL\"" | bw encode | bw create item --session ${token};
    ;;
  "sync")
    token=$(bw unlock --raw);
    bw sync --session ${token};
    ;;
  "login")
    bw login;
    ;;
  "update")
    bw update;
    ;;
esac
