#!/bin/bash

markdown=$1
reveal=~/projects/reveal.js
slides=$reveal/slides.md

rm $slides
cp $markdown $slides
npm start --prefix $reveal

# index.html should have:
#<div class="reveal">
#  <div class="slides">
#    <section data-markdown="slides.md"
#        data-separator="^===+"
#        data-separator-vertical="^---+"
#        data-separator-notes="^Note:"
#        data-charset="iso-8859-15">
#    </section>
#  </div>
#</div>
