#!/usr/bin/env bash

task=$1 

tmux new -s $task \; \
  rename-window 'Research' \; \
  new-window -n 'Source' \; \
  split-window -v \; \
  split-window -h \; \
  send-keys "~/scripts/tomato $task" C-m \; \
  resize-pane -x 40 -y 7 \;
